// constants/userRoles.js

const EMPLOYEE_TYPE_ROLES = {
  MANAGER: 'MANAGER',
  CLEANING_LADY: 'CLEANING_LADY',
  HOST: 'HOST',
  HANDY_MAN: 'HANDY_MAN',
};

const USER_ROLES = {
  ADMIN: 'ADMIN',
  OWNER: 'OWNER',
  ...EMPLOYEE_TYPE_ROLES,
};

// Roles that require a cash register konto
const CASH_REGISTER_ROLES = [
  USER_ROLES.OWNER,
  USER_ROLES.MANAGER,
  USER_ROLES.HOST,
  USER_ROLES.CLEANING_LADY,
  USER_ROLES.HANDY_MAN
];

module.exports = {
  EMPLOYEE_TYPE_ROLES,
  USER_ROLES,
  CASH_REGISTER_ROLES
};
