const APARTMENT_FETCH_START = 'APARTMENT_FETCH_START';
const APARTMENT_FETCH_END = 'APARTMENT_FETCH_END';
const SET_APARTMENT = 'SET_APARTMENT';
const SET_APARTMENT_ERROR = 'SET_APARTMENT_ERROR';
const RESET_APARTMENT = 'RESET_APARTMENT';

const apartmentsActionTypes = {
  APARTMENT_FETCH_START,
  APARTMENT_FETCH_END,
  SET_APARTMENT,
  SET_APARTMENT_ERROR,
  RESET_APARTMENT,
};
export default apartmentsActionTypes;
