const BOOKING_AGENTS_FETCH_START = 'BOOKING_AGENTS_FETCH_START';
const BOOKING_AGENTS_FETCH_END = 'BOOKING_AGENTS_FETCH_END';
const SET_BOOKING_AGENTS = 'SET_BOOKING_AGENTS';
const SET_BOOKING_AGENTS_ERROR = 'SET_BOOKING_AGENTS_ERROR';

const bookingAgentsActionTypes = {
  BOOKING_AGENTS_FETCH_START,
  BOOKING_AGENTS_FETCH_END,
  SET_BOOKING_AGENTS,
  SET_BOOKING_AGENTS_ERROR,
};

export default bookingAgentsActionTypes;
