export const accessToken = 'access_token';

// Password rule - matches server-side validator (models/User.js & users route)
// At least 8 chars, one uppercase letter, one special character.
export const PASSWORD_REGEX =
  /^(?=.*[A-Z])(?=.*[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]).{8,}$/;
export const PASSWORD_RULE_MSG =
  'Password must be at least 8 characters with at least one uppercase letter and one special character';

// User permissions - matches server-side permission definitions
export const USER_PERMISSIONS = {
  // User permissions
  CAN_VIEW_USER: 'CAN_VIEW_USER',
  CAN_CREATE_USER: 'CAN_CREATE_USER',
  CAN_UPDATE_USER: 'CAN_UPDATE_USER',
  CAN_DEACTIVATE_USER: 'CAN_DEACTIVATE_USER',

  // Role permissions
  CAN_VIEW_ROLE: 'CAN_VIEW_ROLE',
  CAN_CREATE_ROLE: 'CAN_CREATE_ROLE',
  CAN_UPDATE_ROLE: 'CAN_UPDATE_ROLE',
  CAN_DEACTIVATE_ROLE: 'CAN_DEACTIVATE_ROLE',

  // Employee permissions
  CAN_VIEW_EMPLOYEE: 'CAN_VIEW_EMPLOYEE',
  CAN_CREATE_EMPLOYEE: 'CAN_CREATE_EMPLOYEE',
  CAN_UPDATE_EMPLOYEE: 'CAN_UPDATE_EMPLOYEE',
  CAN_DEACTIVATE_EMPLOYEE: 'CAN_DEACTIVATE_EMPLOYEE',

  // Apartment permissions
  CAN_VIEW_APARTMENT: 'CAN_VIEW_APARTMENT',
  CAN_CREATE_APARTMENT: 'CAN_CREATE_APARTMENT',
  CAN_UPDATE_APARTMENT: 'CAN_UPDATE_APARTMENT',
  CAN_DEACTIVATE_APARTMENT: 'CAN_DEACTIVATE_APARTMENT',

  // Reservation permissions
  CAN_VIEW_RESERVATION: 'CAN_VIEW_RESERVATION',
  CAN_CREATE_RESERVATION: 'CAN_CREATE_RESERVATION',
  CAN_UPDATE_RESERVATION: 'CAN_UPDATE_RESERVATION',
  CAN_DEACTIVATE_RESERVATION: 'CAN_DEACTIVATE_RESERVATION',

  // Konto permissions
  CAN_VIEW_KONTO: 'CAN_VIEW_KONTO',
  CAN_CREATE_KONTO: 'CAN_CREATE_KONTO',
  CAN_UPDATE_KONTO: 'CAN_UPDATE_KONTO',
  CAN_DEACTIVATE_KONTO: 'CAN_DEACTIVATE_KONTO',

  // Cleaning permissions
  CAN_VIEW_CLEANING: 'CAN_VIEW_CLEANING',
  CAN_CREATE_CLEANING: 'CAN_CREATE_CLEANING',
  CAN_UPDATE_CLEANING: 'CAN_UPDATE_CLEANING',
  CAN_DEACTIVATE_CLEANING: 'CAN_DEACTIVATE_CLEANING',
  CAN_COMPLETE_CLEANING: 'CAN_COMPLETE_CLEANING',
  CAN_VIEW_CLEANING_SENSITIVE_DATA: 'CAN_VIEW_CLEANING_SENSITIVE_DATA',
  CAN_UPDATE_USER_PASSWORD: 'CAN_UPDATE_USER_PASSWORD',
  CAN_WRITE_OFF_RESERVATION: 'CAN_WRITE_OFF_RESERVATION',

  // Report permissions (read-only, one per report)
  CAN_VIEW_UNPAID_RESERVATIONS_REPORT: 'CAN_VIEW_UNPAID_RESERVATIONS_REPORT',
};
