export const accessToken = 'access_token';

// User permissions - matches server-side permission definitions
export const USER_PERMISSIONS = {
  // User permissions
  CAN_VIEW_USER: 'CAN_VIEW_USER',
  CAN_CREATE_USER: 'CAN_CREATE_USER',
  CAN_UPDATE_USER: 'CAN_UPDATE_USER',
  CAN_DELETE_USER: 'CAN_DELETE_USER',

  // Role permissions
  CAN_VIEW_ROLE: 'CAN_VIEW_ROLE',
  CAN_CREATE_ROLE: 'CAN_CREATE_ROLE',
  CAN_UPDATE_ROLE: 'CAN_UPDATE_ROLE',
  CAN_DELETE_ROLE: 'CAN_DELETE_ROLE',

  // Employee permissions
  CAN_VIEW_EMPLOYEE: 'CAN_VIEW_EMPLOYEE',
  CAN_CREATE_EMPLOYEE: 'CAN_CREATE_EMPLOYEE',
  CAN_UPDATE_EMPLOYEE: 'CAN_UPDATE_EMPLOYEE',
  CAN_DELETE_EMPLOYEE: 'CAN_DELETE_EMPLOYEE',

  // Apartment permissions
  CAN_VIEW_APARTMENT: 'CAN_VIEW_APARTMENT',
  CAN_CREATE_APARTMENT: 'CAN_CREATE_APARTMENT',
  CAN_UPDATE_APARTMENT: 'CAN_UPDATE_APARTMENT',
  CAN_DELETE_APARTMENT: 'CAN_DELETE_APARTMENT',

  // Reservation permissions
  CAN_VIEW_RESERVATION: 'CAN_VIEW_RESERVATION',
  CAN_CREATE_RESERVATION: 'CAN_CREATE_RESERVATION',
  CAN_UPDATE_RESERVATION: 'CAN_UPDATE_RESERVATION',
  CAN_DELETE_RESERVATION: 'CAN_DELETE_RESERVATION',

  // Konto permissions
  CAN_VIEW_KONTO: 'CAN_VIEW_KONTO',
  CAN_CREATE_KONTO: 'CAN_CREATE_KONTO',
  CAN_UPDATE_KONTO: 'CAN_UPDATE_KONTO',
  CAN_DELETE_KONTO: 'CAN_DELETE_KONTO',
  CAN_DEACTIVATE_KONTO: 'CAN_DEACTIVATE_KONTO',
};
