// client/src/modules/voiceReservation/types.js

const VOICE_RECORDING_START = 'VOICE_RECORDING_START';
const VOICE_RECORDING_STOP = 'VOICE_RECORDING_STOP';
const VOICE_PROCESSING_START = 'VOICE_PROCESSING_START';
const VOICE_PROCESSING_END = 'VOICE_PROCESSING_END';
const SET_VOICE_RESULT = 'SET_VOICE_RESULT';
const SET_VOICE_ERROR = 'SET_VOICE_ERROR';
const CLEAR_VOICE_RESULT = 'CLEAR_VOICE_RESULT';

const voiceReservationTypes = {
  VOICE_RECORDING_START,
  VOICE_RECORDING_STOP,
  VOICE_PROCESSING_START,
  VOICE_PROCESSING_END,
  SET_VOICE_RESULT,
  SET_VOICE_ERROR,
  CLEAR_VOICE_RESULT,
};

export default voiceReservationTypes;
