const APARTMENTS_FETCH_START = 'APARTMENTS_FETCH_START';
const APARTMENTS_FETCH_END = 'APARTMENTS_FETCH_END';
const SET_APARTMENTS = 'SET_APARTMENTS';
const SET_APARTMENTS_ERROR = 'SET_APARTMENTS_ERROR';
const APARTMENT_FETCH_START = 'APARTMENT_FETCH_START';
const APARTMENT_FETCH_END = 'APARTMENT_FETCH_END';
const SET_APARTMENT = 'SET_APARTMENT';
const SET_APARTMENT_ERROR = 'SET_APARTMENT_ERROR';

const apartmentsActionTypes = {
  APARTMENTS_FETCH_START,
  APARTMENTS_FETCH_END,
  SET_APARTMENTS,
  SET_APARTMENTS_ERROR,
  // apartment action types:
  APARTMENT_FETCH_START,
  APARTMENT_FETCH_END,
  SET_APARTMENT,
  SET_APARTMENT_ERROR,
};
export default apartmentsActionTypes;
