const RESERVATION_FETCH_START = 'RESERVATION_FETCH_START';
const RESERVATION_FETCH_END = 'RESERVATION_FETCH_END';
const SET_RESERVATION = 'SET_RESERVATION';
const SET_RESERVATION_ERROR = 'SET_RESERVATION_ERROR';
const RESET_RESERVATION = 'RESET_RESERVATION';

const reservationActionTypes = {
  RESERVATION_FETCH_START,
  RESERVATION_FETCH_END,
  SET_RESERVATION,
  SET_RESERVATION_ERROR,
  RESET_RESERVATION,
};
export default reservationActionTypes;
