const RESERVATION_FETCH_START = 'RESERVATION_FETCH_START';
const RESERVATION_FETCH_END = 'RESERVATION_FETCH_END';
const SET_RESERVATION = 'SET_RESERVATION';
const SET_RESERVATION_ERROR = 'SET_RESERVATION_ERROR';
const RESET_RESERVATION = 'RESET_RESERVATION';
// reservations (plural) action types
const RESERVATIONS_FETCH_START = 'RESERVATIONS_FETCH_START';
const RESERVATIONS_FETCH_END = 'RESERVATIONS_FETCH_END';
const SET_RESERVATIONS = 'SET_RESERVATIONS';
const SET_RESERVATIONS_ERROR = 'SET_RESERVATIONS_ERROR';

const reservationActionTypes = {
  RESERVATION_FETCH_START,
  RESERVATION_FETCH_END,
  SET_RESERVATION,
  SET_RESERVATION_ERROR,
  RESET_RESERVATION,
  // reservations (plural) action types
  RESERVATIONS_FETCH_START,
  RESERVATIONS_FETCH_END,
  SET_RESERVATIONS,
  SET_RESERVATIONS_ERROR,
};
export default reservationActionTypes;
